name: Autoupdate flake

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  schedule:
    - cron: '0 5 * * *'  # Runs daily at 5:00 UTC

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Updating the flake input references.
      - name: Run flake update command
        run: |
          nix --extra-experimental-features nix-command --extra-experimental-features flakes \
          flake update

      # Commit the updated flake.lock file
      - name: Commit and Push Changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "GitHub Action Bot"
          git add flake.lock
          git commit -m "Automated flake update: $(date +'%Y-%m-%d %H:%M:%S')"
          git push
      # Trigger a build using the CI
      - name: Trigger build
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build.yml
